apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: zipkin
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://openzipkin.github.io/zipkin
    chart: zipkin
    targetRevision: 2.23.2  # hoặc latest stable version
    helm:
      releaseName: zipkin
  destination:
    server: https://kubernetes.default.svc
    namespace: observability
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
