replicaCount: 1
image:
  apiGateway:
    repository: devopshcmus/spring-petclinic-api-gateway
    tag: cedef4f
  discoveryServer:
    repository: devopshcmus/spring-petclinic-discovery-server
    tag: cedef4f
  customersService:
    repository: devopshcmus/spring-petclinic-customers-service
    tag: cedef4f
  vetsService:
    repository: devopshcmus/spring-petclinic-vets-service
    tag: cedef4f
  visitsService:
    repository: devopshcmus/spring-petclinic-visits-service
    tag: "9335095"
  genaiService:
    repository: devopshcmus/spring-petclinic-genai-service
    tag: cedef4f
  adminServer:
    repository: devopshcmus/spring-petclinic-admin-server
    tag: cedef4f
  configServer:
    repository: devopshcmus/spring-petclinic-config-server
    tag: b4d9d20
service:
  apiGateway:
    port: 8080
    nodePort: 30001
  discoveryServer:
    port: 8761
    nodePort: 32439
  customersService:
    port: 8081
  vetsService:
    port: 8083
  visitsService:
    port: 8082
  genaiService:
    port: 8084
  adminServer:
    port: 9090
    nodePort: 31001
  configServer:
    port: 8888
    nodePort: 32001
