replicaCount: 1
image:
  apiGateway:
    repository: devopshcmus/spring-petclinic-api-gateway
    tag: main
  discoveryServer:
    repository: devopshcmus/spring-petclinic-discovery-server
    tag: main
  customersService:
    repository: devopshcmus/spring-petclinic-customers-service
    tag: main
  vetsService:
    repository: devopshcmus/spring-petclinic-vets-service
    tag: main
  visitsService:
    repository: devopshcmus/spring-petclinic-visits-service
    tag: main
  genaiService:
    repository: devopshcmus/spring-petclinic-genai-service
    tag: main
  adminServer:
    repository: devopshcmus/spring-petclinic-admin-server
    tag: main
  configServer:
    repository: devopshcmus/spring-petclinic-config-server
    tag: main
    
service:
  apiGateway:
    port: 8080
    nodePort: 30002
  discoveryServer:
    port: 8761
    nodePort: 32440
  customersService:
    port: 8081
  vetsService:
    port: 8083
  visitsService:
    port: 8082
  genaiService:
    port: 8084
  adminServer:
    port: 9090
    nodePort: 31002
  configServer:
    port: 8888
    nodePort: 32002
