replicaCount: 2
image:
  apiGateway:
    repository: devopshcmus/spring-petclinic-api-gateway
    tag: latest
  discoveryServer:
    repository: devopshcmus/spring-petclinic-discovery-server
    tag: latest
  customersService:
    repository: devopshcmus/spring-petclinic-customers-service
    tag: 29243b2
  vetsService:
    repository: devopshcmus/spring-petclinic-vets-service
    tag: 51fa186
  visitsService:
    repository: devopshcmus/spring-petclinic-visits-service
    tag: latest
  genaiService:
    repository: devopshcmus/spring-petclinic-genai-service
    tag: v2.1.0
  adminServer:
    repository: devopshcmus/spring-petclinic-admin-server
    tag: latest
  configServer:
    repository: devopshcmus/spring-petclinic-config-server
    tag: latest

service:
  apiGateway:
    port: 8080
    nodePort: 30000
  discoveryServer:
    port: 8761
    nodePort: 32438
  customersService:
    port: 8081
  vetsService:
    port: 8083
  visitsService:
    port: 8082
  genaiService:
    port: 8084
  adminServer:
    port: 9090
    nodePort: 31000
  configServer:
    port: 8888
    nodePort: 32000