replicaCount: 1
image:
  apiGateway:
    repository: devopshcmus/spring-petclinic-api-gateway
    tag: ea4d408
  discoveryServer:
    repository: devopshcmus/spring-petclinic-discovery-server
    tag: latest
  customersService:
    repository: devopshcmus/spring-petclinic-customers-service
    tag: ea4d408
  vetsService:
    repository: devopshcmus/spring-petclinic-vets-service
    tag: ea4d408
  visitsService:
    repository: devopshcmus/spring-petclinic-visits-service
    tag: "ea4d408"
  genaiService:
    repository: devopshcmus/spring-petclinic-genai-service
    tag: cedef4f
  adminServer:
    repository: devopshcmus/spring-petclinic-admin-server
    tag: ea4d408
  configServer:
    repository: devopshcmus/spring-petclinic-config-server
    tag: latest
service:
  apiGateway:
    port: 8080
    nodePort: 30001
  discoveryServer:
    port: 8761
    nodePort: 32439
  customersService:
    port: 8081
  vetsService:
    port: 8083
  visitsService:
    port: 8082
  genaiService:
    port: 8084
  adminServer:
    port: 9090
    nodePort: 31001
  configServer:
    port: 8888
    nodePort: 32001
  zipkin:
    port: 9411
    nodePort: 30084
