apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin-server
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: admin-server
  template:
    metadata:
      labels:
        app: admin-server
    spec:
      initContainers:
        - name: wait-for-discovery
          image: busybox:1.36
          command:
            - sh
            - -c
            - >
              echo "Waiting for discovery-server to be ready...";
              until nc -z discovery-server {{ .Values.service.discoveryServer.port }};
              do
                echo "Waiting for discovery-server...";
                sleep 2;
              done;
              echo "Discovery-server is up!";
      containers:
        - name: admin-server
          image: "{{ .Values.image.adminServer.repository }}:{{ .Values.image.adminServer.tag }}"
          ports:
            - containerPort: {{ .Values.service.adminServer.port }}
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: docker
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: http://discovery-server:{{ .Values.service.discoveryServer.port }}/eureka/
            - name: SPRING_APPLICATION_INSTANCE_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: SPRING_CONFIG_SERVER
              value: http://config-server:{{ .Values.service.configServer.port }}
            - name: EUREKA_INSTANCE_HOSTNAME
              value: admin-server

---
apiVersion: v1
kind: Service
metadata:
  name: admin-server
spec:
  selector:
    app: admin-server
  ports:
    - port: {{ .Values.service.adminServer.port }}
      targetPort: {{ .Values.service.adminServer.port }}
