apiVersion: apps/v1
kind: Deployment
metadata:
  name: customers-service
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: customers-service
  template:
    metadata:
      labels:
        app: customers-service
      annotations:
        prometheus.io/scrape: "{{SCRAPE}}"
        prometheus.io/path: "/actuator/prometheus"
        prometheus.io/port: "{{PORT}}"
    spec:
      initContainers:
        - name: wait-for-discovery
          image: busybox:1.36
          command:
            - sh
            - -c
            - >
              echo "Waiting for discovery-server...";
              until nc -z discovery-server {{ .Values.service.discoveryServer.port }};
              do echo "Waiting..."; sleep 2; done;
              echo "discovery-server is up!"
      containers:
        - name: customers-service
          image: "{{ .Values.image.customersService.repository }}:{{ .Values.image.customersService.tag }}"
          ports:
            - containerPort: {{ .Values.service.customersService.port }}
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: docker
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: http://discovery-server:{{ .Values.service.discoveryServer.port }}/eureka/
            - name: SPRING_ZIPKIN_TRACING_ENDPOINT
              value: http://tracing-server:9411/api/v2/spans
            - name: SPRING_APPLICATION_INSTANCE_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: SPRING_APPLICATION_NAME
              value: customers-service
            - name: SPRING_CONFIG_SERVER
              value: http://config-server:{{ .Values.service.configServer.port }}
            - name: EUREKA_INSTANCE_HOSTNAME
              value: customers-service
---
apiVersion: v1
kind: Service
metadata:
  name: customers-service
spec:
  selector:
    app: customers-service
  ports:
    - port: {{ .Values.service.customersService.port }}
      targetPort: {{ .Values.service.customersService.port }}
