
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vets-service
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: vets-service
  template:
    metadata:
      labels:
        app: vets-service
    spec:
      containers:
        - name: vets-service
          image: "{{ .Values.image.vetsService.repository }}:{{ .Values.image.vetsService.tag }}"
          ports:
            - containerPort: {{ .Values.service.vetsService.port }}
---
apiVersion: v1
kind: Service
metadata:
  name: vets-service
spec:
  selector:
    app: vets-service
  ports:
    - port: {{ .Values.service.vetsService.port }}
      targetPort: {{ .Values.service.vetsService.port }}
