
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vets-service
spec:
  selector:
    matchLabels:
      app: vets-service
  template:
    metadata:
      labels:
        app: vets-service
    spec:
      containers:
        - name: vets-service
          image: anwirisme/spring-petclinic-vets-service:main
          ports:
            - containerPort: 8083
